### ISSUE TITLE
Create consumer button themes

### ISSUE THREAD

**Issue by zhongyn** [cerner/terra-consumer#10] opened 2017-08-14 15:58 UTC
# Issue Description
As an application developer, i need predefined consumer button themes available so that i can apply it to terra button using terra theme provider.

Example:
```
import Button from 'terra-button';
import ThemeProvider from 'terra-theme-provider';
import buttonTheme from 'terra-consumer-button-theme';

// merge buttonTheme1 with other variables theme
const myTheme = {otherTheme, ...buttonTheme};
<ThemeProvider theme={myTheme}>
     ...
     <Button ... />
</ThemeProvider>
```
## Tech design
We need a button theme generator which takes a single color as param and returns a POJO contains all the button css custom variables specified by terra button.
```
function buttonThemeGenerator(color) {
   return {
        --terra-button-active-background-color-primary: rgba(color, 0.8);
        --terra-button-active-border-color-primary: color;
       ....
  }
}
```

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

**Comment by alex-bezek** [comment] 2017-08-14 16:39
Where are you putting this `buttonThemeGenerator` function? Is this something we could just do in the terra-consumer theme for button where it takes a single root variable and if given, can generate all the 32 variables as you were talking about? Then clients requiring more customization can supply the specific variables they want to over-write?

**Comment by zhongyn** [comment] 2017-08-14 16:48
@alex-bezek originally i am thinking of running this generator in webpack at asset compile time. It will be called for each concept color.  After the discussion with Brett, we decides to create a consumer-button-themes.css file in terra button which containes predefined css custom properties for each concept color. Will add the tech design link later.

**Comment by alex-bezek** [comment] 2017-08-15 13:14
https://github.com/cerner/terra-core/issues/729
@zhongyn are you closing this issue in favor of the terra-core one?

**Comment by alex-bezek** [comment] 2017-08-24 23:47
closing as duplicate of
https://github.com/cerner/terra-core/issues/729

**Closed by alex-bezek** 2017-08-24 23:47 UTC
